#
# Copyright contributors to the Galasa project 
#
kind: PipelineRun
apiVersion: tekton.dev/v1beta1
metadata:
  generateName: main-framework-build-
  namespace: galasa-tekton
spec:
  params:
  - name: distBranch
    value: main
  - name: refspec
    value: +refs/heads/main:refs/heads/main
  pipelineRef:
    name: framework-repo-build
  serviceAccountName: build-bot
  podTemplate:
    nodeSelector:
      kubernetes.io/arch: amd64
      platform: hdc
    volumes:
    - name: gpggradle
      secret:
        secretName: gpggradle
    - name: gpgkey
      secret:
        secretName: gpgkey
    - name: mavengpg
      secret:
        secretName: mavengpg
  workspaces:
  - name: git-workspace
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
